# ---------------------------------
# general
# ---------------------------------

use_page_scrolling = false
use_pacman_loading = false
article_parse_command = { command = "article_md", options = [ "--format", "html" ] }
client_timeout = 32

# ---------------------------------
# theme
# ---------------------------------

[theme.palette]
background = "default"
foreground = "#908caa"
selection_background = "#26233a"
selection_foreground = "#e0def4"
black = "#191724"
blue = "#31748f"
cyan = "#c4a7e7"
green = "#9ccfd8"
magenta = "#ebbcba"
red = "#eb6f92"
white = "#e0def4"
yellow = "#f6c177"
light_black = "#1f1d2e"
light_white = "#6e6a86"
light_red = "#eb6f92"
light_magenta = "#c4a7e7"
light_green = "#9ccfd8"
light_cyan = "#c4a7e7"
light_blue = "#31748f"
light_yellow = "#f6c177"

[theme.component_style]
title_bar = { back = "black", effect = "bold" }
matched_highlight = { front = "black", back = "yellow"}
metadata = { front = "light white" }
username = { effect = "bold" }
loading_bar = { front = "blue", back = "black"}
header = { front = "black", effect = "bold" }
quote = { front = "white" }
italic = { effect = "italic" }
bold = { effect = "bold" }
single_code_block = { front = "white", back = "light black"}
multiline_code_block = { front = "light black", effect = "bold" }
link = { front = "blue" }
link_id = { front = "blue", back = "black"}
current_story_tag = { front = "light white" }
ask_hn = { front = "red", effect = "bold" }
tell_hn = { front = "yellow", effect = "bold" }
show_hn = { front = "blue", effect = "bold" }
launch_hn = { front = "green", effect = "bold" }

# ---------------------------------
# keymap
# ---------------------------------

[keymap.global_keymap]
open_help_dialog = "?"
quit = ["q", "C-c"]
close_dialog = "esc"
goto_previous_view = ["backspace", "C-p"]
goto_search_view = ["/", "C-s"]
goto_front_page_view = "f1"
goto_all_stories_view = "f2"
goto_ask_hn_view = "f3"
goto_show_hn_view = "f4"
goto_jobs_view = "f5"

[keymap.edit_keymap]
move_cursor_left = ["left", "C-b"]
move_cursor_right = ["right", "C-f"]
move_cursor_to_begin = ["home", "C-a"]
move_cursor_to_end = ["end", "C-e"]
backward_delete_char = "backspace"

[keymap.scroll_keymap]
up = ["up", "k"]
down = ["down", "j"]
page_up = ["page_up", "u"]
page_down = ["page_down", "d"]
top = ["home", "g"]
bottom = ["end", "G"]

[keymap.story_view_keymap]
next_story = "down"
prev_story = "up"
goto_story = "g"
next_page = "n"
prev_page = "p"
cycle_sort_mode = "d"
open_article_in_browser = "o"
open_article_in_article_view = "O"
open_story_in_browser = "s"
goto_story_comment_view = "enter"
next_story_tag = "l"
prev_story_tag = "h"

[keymap.search_view_keymap]
to_navigation_mode = "esc"
to_search_mode = "i"

[keymap.comment_view_keymap]
next_comment = "down"
prev_comment = "up"
next_top_level_comment = "right"
prev_top_level_comment = "left"
next_leq_level_comment = "l"
prev_leq_level_comment = "h"
parent_comment = "u"
open_comment_in_browser = "c"
open_story_in_browser = "s"
open_article_in_browser = "a"
open_article_in_article_view = "A"
open_link_in_browser = "o"
open_link_in_article_view = "O"
toggle_collapse_comment = "tab"

[keymap.article_view_keymap]
open_article_in_browser = "a"
open_link_in_browser = "o"
open_link_in_article_view = "O"
open_link_dialog = "l"

[keymap.link_dialog_keymap]
next = ["down", "down"]
prev = ["up", "up"]
open_link_in_browser = ["o", "enter"]
open_link_in_article_view = "O"
